def array1 = []
def array2 = [:]

pipeline {
    agent any

    options { timestamps() }

    parameters {
        string ( name: 'SERVER_IP', description: 'Enter your sereves ip address (delimiter is \" \" )' )
    }

    stages {
        stage('chekout') {
            steps {
                git url: 'https://github.com/Aleksandr13579/training.git', branch: 'main'
                script {
                    println("$env.WORKDIR")
                }
            }
        }

        stage('two') {
            steps {
                echo 'hello'
            }
        }
    }
}