def array1 = []
def array2 = [:]

pipeline {
    agent any

    options { timestamps() }

    parameters {
        string ( name: 'SERVER_IP', description: 'Enter your sereves ip address (delimiter is \" \" )' )
    }

    stages('chekout my repo') {
        stage('chekout') {
            steps {
                git url: 'https://github.com/Aleksandr13579/training.git', branch: 'main'
                sh 'ls -alrt ./'
            }
        }

        stage('load file') {
            steps {
                sh "cat ${env.WORKSPACE}/training/test.txt"
                script {
                    def myFile = readFile "${env.WORKSPACE}/training/test.txt"
                    def lines = myFile.readLines()
                    def pattern = ~/^([a-zA-Z]+) ([0-9]+)/
                    lines.each {
                        def matcher = pattern.matcher(it)
                        if (matcher.find()) {
                            println(matcher.group(1))
                            println(matcher.group(2))
                        }
                    }
                }
            }
        }
    }
}